# Generated by Django 6.0.4 on 2026-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Folder', '0002_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
