# Generated by Django 6.0.4 on 2026-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.TextField(blank=True, null=True)),
                ('question_uzk', models.TextField(blank=True, null=True)),
                ('question_ru', models.TextField(blank=True, null=True)),
                ('explanation_uz', models.TextField(blank=True, null=True)),
                ('explanation_uzk', models.TextField(blank=True, null=True)),
                ('explanation_ru', models.TextField(blank=True, null=True)),
                ('media', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
