# Generated by Django 6.0.4 on 2026-04-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text_uz', models.TextField(blank=True, null=True)),
                ('answer_text_uzk', models.TextField(blank=True, null=True)),
                ('answer_text_ru', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TestCase.testcase')),
            ],
        ),
    ]
