# Generated by Django 6.0.4 on 2026-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='media',
            field=models.FileField(upload_to='TestCase/'),
        ),
    ]
