# Generated by Django 6.0.4 on 2026-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0002_alter_testcase_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='TestCase/'),
        ),
    ]
