# Generated by Django 6.0.4 on 2026-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0003_alter_testcase_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='explanation_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='explanation_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='explanation_uzk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
