# Generated by Django 6.0.4 on 2026-04-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0004_alter_testcase_explanation_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanswer',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['-pk']},
        ),
    ]
