# Generated by Django 6.0.4 on 2026-04-18 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Group", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="deleted_date",
        ),
        migrations.RemoveField(
            model_name="group",
            name="is_deleted",
        ),
    ]
