# Generated by Django 6.0.4 on 2026-04-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_lock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
