# Generated by Django 6.0.4 on 2026-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('unknown', 'Nomalum'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student')], default='unknown'),
        ),
    ]
