# Generated by Django 6.0.4 on 2026-04-25 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_devicelock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicelock",
            name="ip_address",
        ),
    ]
