# Generated by Django 6.0.4 on 2026-04-20 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserTest", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["-pk"]},
        ),
        migrations.AlterModelTable(
            name="exam",
            table=None,
        ),
    ]
