# Generated by Django 6.0.4 on 2026-04-16 07:07

import apps.RoadSign.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RoadSign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadsign",
            name="icon_path",
            field=models.ImageField(
                upload_to=apps.RoadSign.models.roadsign_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="roadsignfolder",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
