# Generated by Django 6.0.4 on 2026-04-16 07:14

import apps.RoadSign.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RoadSign", "0002_alter_roadsign_icon_path_alter_roadsignfolder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadsignfolder",
            name="icon_path",
            field=models.ImageField(
                upload_to=apps.RoadSign.models.roadsingfolder_upload_path
            ),
        ),
    ]
